/** Stadt Wien brand palette (HEX from the wien.gv.at handbook). */
export const wienColors = {
  wienRot: '#ff0000',
  morgenrot: '#ff5a64',
  morgenrotLight: '#ffced1',
  abendstimmung: '#49274b',
  abendstimmungLight: '#d4c8d4',
  flieder: '#aaaafa',
  fliederLight: '#e6e5fe',
  frischgruen: '#82d282',
  frischgruenLight: '#cdedcd',
  goldgelb: '#e6c828',
  goldgelbLight: '#f8efbd',
  wasserblau: '#73cee5',
  wasserblauLight: '#d2f0ff',
  nebelgrau: '#d6d1ca',
  nebelgrauLight: '#f3f1ef',
  fastSchwarz: '#292929',
  weiss: '#ffffff',
  uiLink: '#1f4baf',
  uiError: '#910000',
  uiSuccess: '#005738',
  uiInteractive: '#4b4b82',
} as const;
